# Makefile for the focaltech touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_0flash_mmi.o

focaltech_0flash_mmi-objs     += focaltech_core.o
focaltech_0flash_mmi-objs     += focaltech_ex_fun.o
focaltech_0flash_mmi-objs     += focaltech_ex_mode.o
focaltech_0flash_mmi-objs     += focaltech_gesture.o
focaltech_0flash_mmi-objs     += focaltech_esdcheck.o
focaltech_0flash_mmi-objs     += focaltech_point_report_check.o


focaltech_0flash_mmi-objs     += focaltech_spi.o

focaltech_0flash_mmi-objs     += focaltech_flash.o
